name: ARG
version: '${project.version}'
main: arg.uottawa.arg.ARG
api-version: 1.19
authors: [ Dish ]
depend: [UltimateAdvancementAPI]
description: The Eye Calls...
commands:
  argstick:
    description: Give yourself the selection stick.
    permission: arg.owner
    permission-message: You don't have permission to execute that command!
    usage: /<command>
  startEvent:
    description: Starts the event.
    permission: arg.owner
    permission-message: You don't have permission to execute that command!
    usage: /<command>